"""Domain enum representing logical section types within a document."""

from enum import StrEnum


class SectionType(StrEnum):
    """Logical categories of sections within a document."""

    SUMMARY = "summary"
    PROFILE = "profile"
    OBJECTIVE = "objective"
    EDUCATION = "education"
    EXPERIENCE = "experience"
    PROJECTS = "projects"
    SKILLS = "skills"
    CERTIFICATIONS = "certifications"
    ACHIEVEMENTS = "achievements"
    PUBLICATIONS = "publications"
    LANGUAGES = "languages"
    CONTACT = "contact"
    INTERESTS = "interests"
    VOLUNTEER = "volunteer"
    AWARDS = "awards"
    OTHER = "other"
    UNKNOWN = "unknown"
    # Job Description specific
    JOB_TITLE = "job_title"
    COMPANY = "company"
    LOCATION = "location"
    EMPLOYMENT_TYPE = "employment_type"
    EXPERIENCE_REQUIRED = "experience_required"
    EDUCATION_REQUIRED = "education_required"
    REQUIRED_SKILLS = "required_skills"
    PREFERRED_SKILLS = "preferred_skills"
    RESPONSIBILITIES = "responsibilities"
    QUALIFICATIONS = "qualifications"
    BENEFITS = "benefits"
    SALARY = "salary"
    KEYWORDS = "keywords"
    OVERVIEW = "overview"
